### ISSUE TITLE
Make available via npm

### ISSUE THREAD

**Issue by lukasoppermann** [toddmotto/foreach#4]
Hey @toddmotto could you please publish this package to npm?

**Comment by lukasoppermann** [comment]
Hey @toddmotto any chance of you publishing it soon? Should not be a huge deal, right? I appreciate you might have quite a busy schedule, but I don't think I can offer any support, as you need to run npm publish with your npmjs account.

The package.json exists already.

**Comment by n457** [comment]
Hi @toddmotto @lukasoppermann, +1 👍
